apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    io.kompose.service: cvat-db
  name: cvat-db
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/mnt/cvat-db"
