apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  type: NodePort
  ports:
   -  name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30008
   -  name: "8090"
      port: 8090
      targetPort: 8090
      nodePort: 30009
  selector:
    io.kompose.service: traefik
status:
  loadBalancer: {}
