apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: traefik
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        io.kompose.network/cvat: "true"
        io.kompose.service: traefik
    spec:
      containers:
        - args:
            - --providers.docker.exposedByDefault=false
            - --providers.docker.network=cvat
            - --entryPoints.web.address=:8080
            - --providers.file.directory=/etc/traefik/rules
          image: traefik:v2.4
          name: traefik
          ports:
            - containerPort: 8080
            - containerPort: 8090
          resources: {}
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: traefik-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: traefik-claim0
          persistentVolumeClaim:
            claimName: traefik-claim0
            readOnly: true
status: {}
