apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cvat-redis
  name: cvat-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cvat-redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/cvat: "true"
        io.kompose.service: cvat-redis
    spec:
      containers:
        - image: redis:4.0-alpine
          name: cvat-redis
          resources: {}
      restartPolicy: Always
status: {}
