apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    io.kompose.service: cvat-svc
spec:
  type: NodePort
  ports:
   - port: 5432
     nodePort: 30533
  selector:
   io.kompose.service: cvat-db
