apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    io.kompose.service: traefik-claim0
  name: traefik-claim0
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/mnt/traefik"
